version: "3.8"
services:
    api:
        build:
            dockerfile: dockerfile
        env_file:
            - .env
        volumes:
            - ./storage:/app/storage
        ports:
            - "8000:80"
        networks:
            - app
    db:
        image: postgres:14.1-alpine
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            - app
volumes:
    db:
        driver: local
networks:
    app:
        driver: bridge
